server:
  name: GoBackend
  profile: dev
  trustedProxies:
    - 127.0.0.1
  port: :8089
  version: 1.0.0
  clientTimeout: 30
  serverTimeout: 30

logger:
  isSplit: false
  cronTime: 0 0 * * *
  logAppDir: ./logs/app
  logRRDir: ./logs/req_res
  logExtDir: ./logs/ext
  maxSize: 5
  maxBackup: 3
  maxAge: 28
  compress: true

databases:
  - kind: sqlserver
    host: localhost
    port: 1433
    username: sa
    password: admin
    timeoutSec: 10
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifeTime: 3600
    schema:
      - user
  - kind: oracle
    host: localhost
    port: 5432
    username: sa
    password: mypassword
    timeoutSec: 10
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifeTime: 3600
    schema:
      - oracle
  - kind: postgres
    host: localhost
    port: 5432
    username: admin111
    password: secret222
    timeoutSec: 10
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifeTime: 3600
    schema:
      - mydatabase333

redis:
  host: localhost
  port: 6379
  password: mypassword
  index: 1
  poolSize: 10
