// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gobaucua/src/main/controller"
	"gobaucua/src/main/repository/repositoryImpl"
	"gobaucua/src/main/service/impl"
)

// Injectors from auth_di.go:

func NewAuthDI() *controller.AuthController {
	iAuthService := impl.NewAuthServiceImpl()
	authController := controller.NewAuthController(iAuthService)
	return authController
}

// Injectors from support_di.go:

func NewSupportDI() *controller.SupportController {
	iSupportRepository := repositoryImpl.NewSupportRepositoryImpl()
	iSupportService := impl.NewSupportServiceImpl(iSupportRepository)
	supportController := controller.NewSupportController(iSupportService)
	return supportController
}

// Injectors from user_di.go:

func NewUserDI() *controller.UserController {
	iUserService := impl.NewUserServiceImpl()
	userController := controller.NewUserController(iUserService)
	return userController
}
