basePath: /api
definitions:
  response.Data:
    properties:
      code:
        example: 2000
        type: integer
      data: {}
      is_success:
        example: true
        type: boolean
      message:
        example: Success
        type: string
      response_at:
        example: "2025-01-14 16:44:47.510"
        type: string
      state:
        example: 8137ce10-305b-42f5-8f14-9c48dd6f23f0
        type: string
    type: object
  response.DataError:
    properties:
      error:
        $ref: '#/definitions/response.Error'
      is_success:
        example: false
        type: boolean
      response_at:
        example: "2025-01-14 16:44:47.510"
        type: string
      state:
        example: 8137ce10-305b-42f5-8f14-9c48dd6f23f0
        type: string
    type: object
  response.Error:
    properties:
      error_code:
        example: 3000
        type: integer
      message:
        example: Invalid RequestLogger
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8089
info:
  contact:
    email: dev.binhtt@gmail.com
    name: Truong Thanh Binh
    url: https://github.com/BevisDev
  description: There are APIs in project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/BevisDev
  title: API Specification
  version: "1.0"
paths:
  /db:
    get:
      description: Check health DB System
      produces:
      - application/json
      responses:
        "200":
          description: Successful
          schema:
            additionalProperties: true
            type: object
      summary: Ping DB API
      tags:
      - Check Health
  /ping:
    get:
      description: Check health system
      produces:
      - application/json
      responses:
        "200":
          description: Successful
          schema:
            additionalProperties: true
            type: object
      summary: Ping System API
      tags:
      - Check Health
  /redis:
    get:
      description: Check health Redis System
      produces:
      - application/json
      responses:
        "200":
          description: Successful
          schema:
            additionalProperties: true
            type: object
      summary: Ping Redis API
      tags:
      - Check Health
  /signin:
    post:
      consumes:
      - application/json
      description: sign in web app
      produces:
      - application/json
      responses:
        "200":
          description: Successful
          schema:
            $ref: '#/definitions/response.Data'
        "400":
          description: Client Error
          schema:
            $ref: '#/definitions/response.DataError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/response.DataError'
      security:
      - AccessTokenAuth: []
      summary: Sign In API
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - application/json
      description: sign up web app
      produces:
      - application/json
      responses:
        "200":
          description: Successful
          schema:
            $ref: '#/definitions/response.Data'
        "400":
          description: Client Error
          schema:
            $ref: '#/definitions/response.DataError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/response.DataError'
      security:
      - AccessTokenAuth: []
      summary: Sign Up API
      tags:
      - Auth
securityDefinitions:
  AccessTokenAuth:
    description: Description for what is this security definition being used
    in: header
    name: AccessToken
    type: apiKey
swagger: "2.0"
